CODETOOLS-7902936 Stray VM warnings in forked PrintPropertiesMain lead to hard to debug XML parse exception
openjdk/jmh pull request #41
Opened 2021-05-21 02:27 UTC by retronym

- Recover from stray output before the XML prelude
  - Report the output in the exception otherwise
  - Silence VM warnings in PrintPropertiesMain when JEP-158 (-Xlog:) is available (JRE 9+)

2021-05-21 02:32 UTC, retronym commented
This code path is only exercised when specifying an alternative `-jvm`, which doesn't appear to be done in the JMH test suite, presumably because of the hassle of requiring multiple JVMs.

I manually tested the change by:

 - Running just the diagnostic on a server that gives the VM warnings about duplicate cpusets. The error message included the VM warning.
 - JMH worked again on that machine with the commit that adds `-Xlog:all=error`
 - Locally, I added `System.out.println("VM OUTPUT")` to `PrintPropertiesMain` and tested that the recovery logic worked.

2021-05-21 08:08 UTC, shipilev requested changes
I see little sense in trying to recover here. The stray VM output can come in the middle of that XML dump too. I would prefer to cover the "hard to debug" part only: dump the proper diagnostics and then fail hard. We can probably print the helpful message how to shun the VM warnings, if user is so inclined?

2021-05-21 08:08 UTC, shipilev commented on jmh-core/src/main/java/org/openjdk/jmh/runner/Runner.java
> +
I think pushing `-Xlog:` to unsuspecting VMs is asking for trouble, even with `IgnoreUnrecognizedVMOptions`. Let's not do this.

2021-05-21 08:08 UTC, shipilev commented on jmh-core/src/main/java/org/openjdk/jmh/util/Utils.java
> +            } catch (InvalidPropertiesFormatException ex) {
Move this `catch` block to the existing `try-catch` block. Make the whole thing failing hard without trying to recover. Print the output contents in the exception.

2021-05-21 08:08 UTC, shipilev commented on jmh-core/src/main/java/org/openjdk/jmh/util/Utils.java
> +                String output = new String(baos.toByteArray(), Charset.defaultCharset());
I suspect that since we are reading from the console, we need to use `Utils.guessConsoleCharset()` instead of trusting the default one.

2021-05-22 01:54 UTC, retronym commented
> I would prefer to cover the "hard to debug" part only: dump the proper diagnostics and then fail hard

No worries, I thought I'd throw the whole gamut in here and let you decide what to include. 

> We can probably print the helpful message how to shun the VM warnings, if user is so inclined?

What advice could we give? The use can't currently add JVM options to the `PrintPropertiesMain` forked JVM.

FWIW, I haven't yet found a way to reconfigure the Linux system to avoid my particular VM warning. Not necessarily because its hard to fix, but more because I'm clueless about this part of Linux. At some point an OS upgrade would make sense but that could introduce a discontinuity into our historical benchmark results.

The other options I haven't explored, but seem easy enough to implement are:
  - use a temporary file to transfer the XML. The parent process could create the file and pass its name as an argument to `PrintPropertiesMain`.
  - extend use `BinaryLinkServer` to allow the the properties to be pushed back over a socket.

2021-05-25 16:47 UTC, shipilev commented
> What advice could we give? The use can't currently add JVM options to the `PrintPropertiesMain` forked JVM.

Argh. I thought we can ask user to provide `-Xlog` shun manually.

> * use a temporary file to transfer the XML. The parent process could create the file and pass its name as an argument to `PrintPropertiesMain`.

Yes, temp file would be cleanest option here. Call `FileUtils.tempFile("properties")` in host VM, pass the name of that file as the first argument to `PrintPropertiesMain`, let it write there, read the file back. This whole `stdout` mess is why JMH eventually moved to `BinaryLinkServer/Client` -- relying on standard streams to be pristine is wishful thinking :(

2021-05-26 04:10 UTC, retronym commented
> Yes, temp file would be cleanest option here

Done. That enabled a small cleanup to implement this in terms of `tryWith`.

I've also added a test that exercises `PrintPropertiesMain` by passing `-jvm current_jdk/bin/./java`. That looks like a different VM to `Runner` without actually needing a second JVM around to run tests.

2021-05-26 06:59 UTC, shipilev approved these changes
This is good. Rename the test file, and we are good to go.

2021-05-26 06:59 UTC, shipilev commented on jmh-core-it/src/test/java/org/openjdk/jmh/it/jvmoption/JvmOption.java
> +public class JvmOption {
This should be `JvmOptionTest` to match the naming convention for the tests.

2021-05-26 08:04 UTC, shipilev commented
/sponsor

2021-05-26 08:05 UTC, retronym commented
Just pushed an extra commit to remove an unused import I introduced, hope I haven't provoked a race condition in the bot!

2021-05-26 08:06 UTC, retronym commented
Clever bot!

2021-05-26 08:06 UTC, retronym commented
/integrate

2021-05-26 08:07 UTC, shipilev commented
Ok, now waiting for GHAs to complete again.

2021-05-26 09:22 UTC, shipilev commented
/sponsor

2021-05-26 09:23 UTC, closed without merging