Fix wrong options while using async-profiler v2
openjdk/jmh pull request #65
Opened 2022-03-07 08:39 UTC by chhsiao90

Previously, the jmh will call async-profiler with output=flamegraph,
which the 'output' option is not a valid option for both async-profiler
v1 and v2.

For jfr format, this class will call the profiler with
'start,file=name.jfr', async-profiler can get the output format from the
extension corretly, so we don't need to have a redundant option like
'start,jfr,file=name.jfr'.

For other formats like flamegraph, this class call the dump separately
with the format option included in the option, like
`flamegraph,file=dump.html`.

**Reference**

- v1: https://github.com/jvm-profiling-tools/async-profiler/blob/v1.8.7/src/arguments.cpp
- v2: https://github.com/jvm-profiling-tools/async-profiler/blob/v2.7/src/arguments.cpp

2022-03-07 08:47 UTC, chhsiao90 commented
OCA signed.

2022-03-07 08:47 UTC, chhsiao90 commented
/signed

2022-03-23 11:29 UTC, shipilev commented
Hi, please change the PR title to "7903125: JMH: async profiler uses wrong option for profiler output" to get the issue properly hooked. I'll test the change meanwhile...

2022-03-23 12:03 UTC, shipilev requested changes
I tested with 1.x and 2.x (with strong option verification) async-profiler branches and all variants of output, and I think "text" requires a bit of touch-up, as it rejects "summary" too:

```
diff --git a/jmh-core/src/main/java/org/openjdk/jmh/profile/AsyncProfiler.java b/jmh-core/src/main/java/org/openjdk/jmh/profile/AsyncProfiler.java
index 084393cf..fe21c6b3 100644
--- a/jmh-core/src/main/java/org/openjdk/jmh/profile/AsyncProfiler.java
+++ b/jmh-core/src/main/java/org/openjdk/jmh/profile/AsyncProfiler.java
@@ -369,7 +369,11 @@ public final class AsyncProfiler implements ExternalProfiler, InternalProfiler {
             switch (outputType) {
                 case text:
                     File out = outputFile("summary-%s.txt");
-                    dump(out, "summary,flat=" + flat + ",traces=" + traces);
+                    if (isVersion1x) {
+                        dump(out, "summary,flat=" + flat + ",traces=" + traces);
+                    } else {
+                        dump(out, "flat=" + flat + ",traces=" + traces);
+                    }
                     try {
                         for (String line : FileUtils.readAllLines(out)) {
                             pw.println(line);
```

2022-03-23 12:05 UTC, chhsiao90 commented
Thanks for the review and testing, will address this issue!

2022-03-23 12:07 UTC, shipilev commented
Just add that little patch, and I think we are fine otherwise.

2022-03-23 12:10 UTC, chhsiao90 commented
Patch applied!

2022-03-23 19:28 UTC, shipilev commented
I see there are some "JMH Pre-Integration Tests" failures. If you merge from current master, they should be gone. Once those tests are clean, feel free to say `/integrate`.

2022-03-23 21:34 UTC, chhsiao90 commented
/integrate

2022-03-23 21:47 UTC, chhsiao90 commented
/integrate

2022-03-25 18:48 UTC, shipilev commented
/sponsor

2022-03-25 18:48 UTC, closed without merging