CODETOOLS-7903215: JMH: xperfasm throws incorrect error when xperf is not available
openjdk/jmh pull request #72
Opened 2022-05-16 09:49 UTC by XIACYBING

When Windows Performance Toolkit is not installed in Windows environment, WinPerAsmProfiler will start abnormally and throw wrong message due to wrong operation.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Issue
 * [CODETOOLS-7903215](https://bugs.openjdk.org/browse/CODETOOLS-7903215): JMH: xperfasm throws incorrect error when xperf is not available

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jmh pull/72/head:pull/72` \
`$ git checkout pull/72`

Update a local copy of the PR: \
`$ git checkout pull/72` \
`$ git pull https://git.openjdk.org/jmh pull/72/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 72`

View PR using the GUI difftool: \
`$ git pr show -t 72`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jmh/pull/72.diff">https://git.openjdk.org/jmh/pull/72.diff</a>

</details>

2022-05-16 09:53 UTC, XIACYBING commented
@shipilev  Can you please help review this PR?

2022-05-16 10:43 UTC, XIACYBING commented
/signed

2022-06-22 10:07 UTC, shipilev requested changes
Ah, good find. Let's not rely on `Utils.tryWith` returning the `ArrayList`, because that would shun the messages on some failure paths. Instead, let's do this:

```
        Collection<String> errsStop = Utils.tryWith(path, "-stop");
        if (!errsStop.isEmpty()) {
            throw new ProfilerException(MSG_UNABLE_STOP + ": " + errsStop.toString());
        }
```

2022-06-23 09:02 UTC, XIACYBING commented
> Ah, good find. Let's not rely on `Utils.tryWith` returning the `ArrayList`, because that would shun the messages on some failure paths. Instead, let's do this:
> 
> ```
>         Collection<String> errsStop = Utils.tryWith(path, "-stop");
>         if (!errsStop.isEmpty()) {
>             throw new ProfilerException(MSG_UNABLE_STOP + ": " + errsStop.toString());
>         }
> ```

This is indeed a better way, the code has been modified.

2022-06-23 10:14 UTC, shipilev approved these changes
This is good.

2022-06-24 02:15 UTC, XIACYBING commented
/integrate

2022-06-24 06:11 UTC, shipilev commented
/sponsor

2022-06-24 06:12 UTC, closed without merging